/**
 * Every UW Madison building + apartments and dorms (names only).
 * Coordinates live in data/uw_buildings_and_housing.json for the app.
 * Regenerate: node scripts/build_uw_buildings_and_housing.js
 */

export const UW_BUILDINGS_AND_HOUSING_NAMES: readonly string[] = [
  "10 East Doty at Block89",
  "1610 University Ave.",
  "1910 Linden Dr.",
  "1932 Linden Drive",
  "206 Bernard Ct.",
  "25 West Main Street",
  "306 West Main",
  "33 East Main at Block89",
  "420 West",
  "44 East Mifflin",
  "502 Herrick Dr.",
  "699 Station Apartments",
  "A8 China",
  "ABC for Health",
  "Aberdeen Apartments",
  "AC Hotel Madison Downtown",
  "Acacia Fraternity",
  "Adams Hall",
  "Adams Residence Hall",
  "Adria",
  "Agricultural Dean's Residence",
  "Agricultural Engineering",
  "Agricultural Engineering Laboratory",
  "Agricultural Hall",
  "Agricultural Heating Station",
  "Air Force ROTC",
  "Akasha House",
  "Alchemy Apartments",
  "Allen House",
  "Alpha Chi Omega Sorority",
  "Alpha Delta Phi Fraternity",
  "Alpha Epsilon Phi Sorority",
  "Alpha Gamma Rho Fraternity",
  "Alpha Sigma Phi Fraternity",
  "Alpha Xi Delta Sorority",
  "Ambassador West Apartments",
  "Ambrosia Co-Op",
  "American Exchange Block",
  "Animal Science Building",
  "Armory and Gymnasium",
  "Art Building",
  "Art Lofts",
  "Arthur D. Hasler Laboratory of Limnology",
  "Athletic Operations Building",
  "Atmosphere",
  "Atmospheric & Oceanic Sciences",
  "Audre Lorde Co-Op",
  "Avenir Apartments",
  "Babcock Hall",
  "Bakke Recreation & Wellbeing Center",
  "Bardeen Medical Laboratories",
  "Barnard Hall",
  "Barnard Residence Hall",
  "Barracuda Condos",
  "Bartell Theatre",
  "Bascom Hall",
  "Bassett Walk",
  "Bassett Warehouse Apartments",
  "Bayliss Cooperative",
  "Bedford Court Condominiums",
  "Beecroft House",
  "Bel Mora Apartments",
  "Bell Wood Apartments",
  "Best Western Premier Park Hotel",
  "Beta Theta Pi Fraternity",
  "Bethel Lutheran Church",
  "Bill’s Key Shop & Locksmith Service",
  "Biotron Laboratory",
  "Birge Hall",
  "Block 100",
  "Botany Greenhouse",
  "BP",
  "Bradley Hall",
  "Bradley Memorial Building",
  "Bradley Residence Hall",
  "Brat Stand",
  "Brogarden",
  "Brogden Psychology Building",
  "Budget Bicycle Center - New Bicycles",
  "Burrows Block at Block89",
  "Business School",
  "Butler Plaza",
  "Calimar Apartments",
  "Camp Randall Stadium",
  "Camp Randall Stockade",
  "Campus Hardware True Value",
  "Capitol Centre Apartments",
  "Capitol Centre Market",
  "Capitol Chop House",
  "Capitol Hill Apartments",
  "Capitol Lakes",
  "Capitol Parkside Condos",
  "Capitol Point Condos",
  "Capitol Square North Garage",
  "Capitol Square Station (EB)",
  "Capitol Square Station (WB)",
  "Capitol West",
  "Capitol West Townhouses",
  "Carillon Tower",
  "Carson Gulley",
  "Carson Gulley Center",
  "Central Library",
  "Chabad at the University of Wisconsin",
  "Chadbourne",
  "Chadbourne Residence Hall",
  "Chamberlin Hall",
  "Chapter",
  "Chazen Museum of Art",
  "Cheba Hut",
  "Chemistry Building",
  "Chen's Noodles & Dumplings",
  "Chi Omega Sorority",
  "Chi Psi Fraternity",
  "Churchill Building",
  "City Place Apartments",
  "City View Apartments",
  "City-County Building",
  "Cole Hall",
  "Collegiate Madison",
  "Commercial Bank building",
  "Computer Sceinces Building",
  "D.C. Smith Greenhouse",
  "Dairy Barn",
  "Dairy Cattle Instruction & Research Center",
  "Dane County Courthouse",
  "Dane County Public Safety Building",
  "Daniel K. & Mary Jane Tenney Residence",
  "David Johnson House",
  "Dejope",
  "Dejope Hall",
  "Dejope Residence Hall",
  "Delta Chi Fraternity",
  "Delta Delta Delta Sorority",
  "Delta Gamma Sorority",
  "Delta Theta Sigma Fraternity",
  "Delta Upsilon Fraternity",
  "DeLuca Biochemical Sciences Building",
  "DeLuca Biochemistry Building",
  "DeLuca Biochemistry Laboratories",
  "Domain",
  "Doty School Condominiums",
  "Dowling Apartments",
  "Doyle Administration Building",
  "Dunsinane Condos",
  "Eagle Heights",
  "East Campus Station (EB)",
  "East Campus Station (WB)",
  "Echo Tap and Grill",
  "Edmund J. & Ida Hart Residence",
  "Education Building",
  "Educational Sciences",
  "Edward F. Riley Rental House",
  "Elizabeth S. & Dr. Reginald H. Jackson Residence",
  "Embassy Suites",
  "Engineering Centers Building",
  "Engineering Hall",
  "Engineering Research Building",
  "Environmental Health and Safety Building",
  "Enzyme Institute",
  "Equinox",
  "Estacion Inka",
  "Eugene A. Gilmore House",
  "Extension Building",
  "Field House",
  "First Congregational Church",
  "First United Methodist Church",
  "Fleet and Service Garage",
  "Fluno Center",
  "Four Lakes",
  "Freethought Hall",
  "French House",
  "Gamma Phi Beta Fraternity",
  "Genetics-Biotechnology Center Building",
  "Gilman House",
  "Gilman Plaza",
  "Gordon Commons",
  "Gordon Dining and Event Center",
  "Grace Episcopal Church",
  "Graduate by Hilton Madison",
  "Grainger Hall",
  "Grand Central",
  "Great Beginnings",
  "Grimm Book Bindery",
  "Hamel Music Center",
  "Hamilton Plaza Apartments",
  "Hamilton Point Apartments",
  "Hampton Inn & Suites Madison / Downtown",
  "Hanson Biomedical Sciences Building",
  "Harlow Primate Laboratory",
  "Harold C. Bradley House",
  "Haven",
  "Hawthorne Apartments",
  "Helen C White",
  "Helen C. White Hall",
  "Hilton Garden Inn",
  "Hilton Madison Monona Terrace",
  "Hiram Smith Hall",
  "Hiram Smith Hall Annex",
  "Holt Center",
  "Holy Redeemer Catholic Church",
  "Hoofers Sailing Club",
  "Horse Barn",
  "Horticulture",
  "Hotel Lorraine",
  "Hovde Building",
  "Hoyt Lodge",
  "Hoyt Lodge Garage",
  "Humanities",
  "Humbucker Apartments",
  "Humphrey Hall",
  "Hyatt Place",
  "Inez Apartments",
  "Ingraham Hall",
  "Integrative Biology Research Building",
  "International Co-Op",
  "Isaiah Weaver Residence",
  "J.W. Hobbins Rental House",
  "Jay's",
  "John M. Olin House",
  "Johnson Bank",
  "Jones House",
  "Jordan's Big Ten Pub",
  "Jorns Hall",
  "Kappa Kappa Gamma Sorority",
  "Keller Building",
  "Kellner Hall",
  "Kennedy Building",
  "King Hall",
  "King St. Station",
  "Kohl Center",
  "Kronshage",
  "La Ciel",
  "LaBahn Arena",
  "Lake Park Apartments",
  "Lakeshore",
  "Lamp House",
  "Langdon Hall Apartments",
  "Lark at Kohl",
  "Lark at Randall",
  "Lathrop Hall",
  "Law Building",
  "Leopold Residence Hall",
  "Levin Hall",
  "Lewis E. & Ella Stevens Residence",
  "Lexington Apartments",
  "Linden Drive Ramp",
  "Livestock Laboratory",
  "Liz Waters",
  "Lothlorien Co-Op",
  "Lowell Center",
  "Lumen House",
  "Luther Memorial Church",
  "Mack House",
  "Madison Building Inspection",
  "Madison Children's Museum",
  "Madison Club",
  "Madison Concourse Hotel",
  "Madison Fire Station No. 1",
  "Madison Fire Station No. 4",
  "Madison LDS",
  "Madison Masonic Center",
  "Madison Municipal Building",
  "Madison Property Management Inc.",
  "Madtown Wash",
  "Majestic",
  "Major James R. & Lois Mears Residence",
  "Mall Concourse/State Street Maintenance",
  "Manchester Place",
  "Master Hall",
  "Materials Science and Engineering",
  "McArdle Building",
  "McClain Athletic Facility",
  "McDonald's",
  "Meat Science and Animal Biologics Discovery",
  "Mechanical Engineering Building",
  "Medical Sciences",
  "Meiklejohn House",
  "Memorial Arch",
  "Memorial Library",
  "Memorial Union",
  "Merit Residence Hall",
  "Metropolitan Place",
  "Microbial Sciences Building",
  "Mifflander Apartments",
  "Milwaukee Road Depot",
  "Mister Car Wash",
  "Moore Hall",
  "Morgridge",
  "Morgridge Center",
  "Morgridge Hall",
  "Mosse Humanities",
  "Mrs. S.H. Carpenter Rental House",
  "Muscle & Meat Science Research Laboratory",
  "Music Hall",
  "Nancy Nicholas Hall",
  "New Wine Co-op",
  "Nicholas Recreation Center",
  "Nicholas-Johnson Pavilion and Plaza",
  "Noland Hall",
  "Nolen Shore Condominiums",
  "Noodles & Company",
  "North Hall",
  "Norwegian-American Genealogical Center & Naeseth Library",
  "Nottingham Cooperative",
  "NoVo Apartments",
  "Nursing",
  "Nutritional Sciences",
  "OakTree Apartments",
  "Ofek Shalom Co-Op",
  "Ogg Residence Hall",
  "ōLiv Madison",
  "One East Main at Block89",
  "OPN Architects",
  "Orchard Station (EB)",
  "Orchard Station (WB)",
  "Orpheum Theatre",
  "Ovation 309",
  "Overture Center",
  "Overture Center for the Arts",
  "Overture Center Ramp",
  "Paras Building",
  "Park Place",
  "Park Regent Apartments",
  "Park Terrace West",
  "Pharmacy Building",
  "Phi Delta Theta Fraternity",
  "Phi Kappa Sigma Fraternity",
  "Phillips Hall",
  "Pi Beta Phi Sorority",
  "Pi Kappa Alpha Fraternity",
  "Pi Kappa Phi Fraternity",
  "Pi Lambda Phi Fraternity",
  "Plant Sciences",
  "Porta Bella",
  "Poultry Research Laboratory",
  "Pres House",
  "Pres House Apartments",
  "Pricked Piercing",
  "Prost!",
  "Psychology",
  "Pyle Center",
  "Quisling Terrace",
  "Radio Hall",
  "Ragstock",
  "RAYGUN",
  "Red Rock Saloon",
  "Red Square Flowers",
  "Regent Market Co-Op",
  "Renaissance Apartments",
  "Rivendell Co-Op",
  "Robert M. Bock Laboratories",
  "Robert M. Lafollette School of Public Affairs",
  "Robert W. Kastenmeier Federal Courthouse",
  "Rochdale International Co-op",
  "Round House",
  "Russell Laboratories",
  "Rust-Schreiner Hall",
  "Saint Paul University Catholic Center",
  "School of Social Work Building",
  "Science Hall",
  "Sellery",
  "Sellery Hall",
  "Sellery Residence Hall",
  "Service Memorial Institute",
  "Sheelin Apartments",
  "Sigma Alpha Epsilon Fraternity",
  "Sigma Delta Tau Sorority",
  "Sigma Lambda Gamma Sorority",
  "Sigma Pi Fraternity",
  "Skylight Apartments",
  "Slichter Hall",
  "Slichter Residence Hall",
  "Smith",
  "Smith Hall",
  "Smith Residence Hall",
  "Soap Opera",
  "Social Sciences",
  "Soils Building",
  "South Hall",
  "Southeast Campus Ramp",
  "Spring Brook Row Apartments",
  "St. John's Lutheran Church",
  "Starbucks",
  "State Street (EB)",
  "State Street (WB)",
  "State Street Brats",
  "State Street Capitol Ramp",
  "Steenbock Memorial Library",
  "Steensland House",
  "Sterling Hall",
  "Stock Pavilion",
  "Stony Hill Antiques and Gallery",
  "Stop N Shop",
  "Stovall Building (Wisconsin State Laboratory of Hygiene)",
  "Suhr Building",
  "Sullivan Hall",
  "Summit Ave. Cooperative",
  "Surfside",
  "Swenson House",
  "Tau Kappa Epsilon Fraternity",
  "Taylor Hall",
  "Teacher Education",
  "Tenney Plaza",
  "Tenney Plaza Ramp",
  "The Baskerville",
  "The BBQ Stand",
  "The Buckingham Inn",
  "the church in Madison",
  "The Continental",
  "The Crossing",
  "The Depot",
  "The Eleanor",
  "The Embassy",
  "The Flats at 402",
  "The Gilman Apartments",
  "The Heights",
  "The HUB Madison",
  "The Jackman Building",
  "The James",
  "The Lurican",
  "The Lux",
  "The Nitty Gritty",
  "The Old Fashioned",
  "The Palisades",
  "The Pressman",
  "The Regent Apartments",
  "The Rigby Pub",
  "The Rive Madison",
  "The Statesider",
  "The Towers on State",
  "The Waterfront Apartments",
  "Theta Delta Chi Fraternity",
  "Time Square Apartments",
  "Tommy G Thompson Center",
  "Trainors Store",
  "Triangle Fraternity",
  "Tripp Hall",
  "Tripp Residence Hall",
  "Tuscan Place",
  "U.S. Bank Plaza",
  "Union South",
  "United States Post Office",
  "University Avenue Ramp",
  "University Gables",
  "University Square",
  "US Dairy Forage Research Center",
  "UW Credit Union",
  "UW Foundation",
  "UW Hillel",
  "Uw Hospital",
  "UW-Madison Police and Security Building",
  "Van Hise Hall",
  "Van Slyke House",
  "Van Vleck",
  "Vantage Point",
  "Varsity Campus Apartments",
  "Veterinary Medicine",
  "Veterinary Medicine South",
  "Vilas Communication Hall",
  "Vintage Spirits and Grill",
  "Virtue",
  "Walnut Street Greenhouses",
  "Walnut Street Heating & Cooling Plant",
  "Wando's Bar & Grill",
  "Washburn Observatory",
  "Washington Court Apartments",
  "Washington Plaza Apartments",
  "Water Science & Engineering Laboratory",
  "Waters Hall",
  "Waters Residence Hall",
  "Wendt Commons",
  "West Campus Cogeneration Facility",
  "West Washington Place",
  "West Washington Self Storage",
  "Wiedenbeck Apartments",
  "Willett S. Main Rental Duplex",
  "Willett S. Main Rental house",
  "William H. Sewell Social Sciences Building",
  "William S. Middleton Office Building",
  "Wilson Bay Apartments",
  "Wisconsin Department of Children And Familes",
  "Wisconsin Department of Health Services",
  "Wisconsin Department of Justice",
  "Wisconsin Department of Natural Resources",
  "Wisconsin Department of Public Instruction",
  "Wisconsin Design Team",
  "Wisconsin Energy Institute",
  "Wisconsin Historical Society",
  "Wisconsin Institute for Discovery",
  "Wisconsin Lutheran Chapel",
  "Wisconsin National Primate Research Center",
  "Wisconsin Primate Center",
  "Wisconsin State Capitol",
  "Wisconsin Veterans Museum",
  "Wisconsin Veterinary Diagnostics Laboratory",
  "Witte",
  "Witte Hall",
  "Witte Residence Hall",
  "X01",
  "YWCA Madison",
  "Zeta Beta Tau Fraternity",
]
